# Generated by iptables-save v1.6.0 on Sat Apr  3 22:29:44 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Sat Apr  3 22:29:44 2021
# Generated by iptables-save v1.6.0 on Sat Apr  3 22:29:44 2021
*mangle
:PREROUTING ACCEPT [13594:3831315]
:INPUT ACCEPT [13582:3830667]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [18871:6561004]
:POSTROUTING ACCEPT [18871:6561004]
-A INPUT -p udp -m udp --sport 5060 -j DSCP --set-dscp 0x18
-A INPUT -p udp -m udp --dport 5060 -j DSCP --set-dscp 0x18
-A INPUT -p udp -m udp --sport 10000:20000 -j DSCP --set-dscp 0x2e
-A OUTPUT -p udp -m udp --sport 5060 -j DSCP --set-dscp 0x18
-A OUTPUT -p udp -m udp --dport 5060 -j DSCP --set-dscp 0x18
-A OUTPUT -p udp -m udp --sport 10000:20000 -j DSCP --set-dscp 0x2e
-A OUTPUT -p udp -m udp --dport 10000:20000 -j DSCP --set-dscp 0x2e
COMMIT
# Completed on Sat Apr  3 22:29:44 2021
# Generated by iptables-save v1.6.0 on Sat Apr  3 22:29:44 2021
*filter
:INPUT ACCEPT [13835685:6945493349]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [6467921:5786322799]
-A INPUT -p udp -m udp --dport 5060 -m string --string "User-Agent: friendly-scanner" --algo bm --to 65535 -j REJECT --reject-with icmp-port-unreachable
-A INPUT -p udp -m string --string "friendly-scanner" --algo bm --to 600 -m udp --dport 5060 -j DROP
-A INPUT -p udp -m string --string "sipcli/v" --algo bm --to 600 -m udp --dport 5060 -j DROP
-A INPUT -p udp -m string --string "sipvicious" --algo bm --to 600 -m udp --dport 5060 -j DROP
COMMIT
# Completed on Sat Apr  3 22:29:44 2021
